// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACXP0P358naFFQvb98_JOqxtoZs-aeuho',
    appId: '1:696259143481:web:bf6362a169ccd7d4fd6ae8',
    messagingSenderId: '696259143481',
    projectId: 'my-api-endpoint',
    authDomain: 'my-api-endpoint.firebaseapp.com',
    storageBucket: 'my-api-endpoint.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsmFGxromjfoir-rC8CSDU46peqpmpFaQ',
    appId: '1:696259143481:android:5868a03348257593fd6ae8',
    messagingSenderId: '696259143481',
    projectId: 'my-api-endpoint',
    storageBucket: 'my-api-endpoint.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAN-11CAG6XrRlDhmmIcUcwPDVKMlngaqM',
    appId: '1:696259143481:ios:dd3d561f60a583e8fd6ae8',
    messagingSenderId: '696259143481',
    projectId: 'my-api-endpoint',
    storageBucket: 'my-api-endpoint.appspot.com',
    iosClientId: '696259143481-326u8li1cvmfj3enoj8n1gd5lb21j59i.apps.googleusercontent.com',
    iosBundleId: 'com.example.bubbleTeaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAN-11CAG6XrRlDhmmIcUcwPDVKMlngaqM',
    appId: '1:696259143481:ios:4d496ec5315f3ad4fd6ae8',
    messagingSenderId: '696259143481',
    projectId: 'my-api-endpoint',
    storageBucket: 'my-api-endpoint.appspot.com',
    iosClientId: '696259143481-7pbedkm1gh6s2kd8ff0m1ese13h3i9c3.apps.googleusercontent.com',
    iosBundleId: 'com.example.bubbleTeaApp.RunnerTests',
  );
}
